name: Deploy Laravel via FTPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: Produção
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, ctype, json, bcmath, pdo_mysql
          coverage: none

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências PHP
        run: |
          composer install \
            --no-dev \
            --optimize-autoloader \
            --prefer-dist \
            --no-interaction

      - name: Instalar dependências Node
        run: npm install

      - name: Build Frontend
        run: npm run build

      - name: Limpar arquivos desnecessários
        run: |
          rm -rf node_modules
          rm -rf tests
          rm -rf .git
          rm -rf .github

      - name: Compactar aplicação
        run: |
          zip -r deploy.zip . \
            -x "*.git*" \
            -x "storage/logs/*" \
            -x ".env"

      - name: Instalar lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Enviar ZIP via FTPS
        run: |
          lftp <<EOF
          set ftp:ssl-force true
          set ftp:ssl-protect-data true
          set ssl:verify-certificate no

          open -u "${{ secrets.FTP_USER }}","${{ secrets.FTP_PASS }}" \
            -p 21 \
            ${{ secrets.FTP_HOST }}

          put deploy.zip

          bye
          EOF

      - name: Executar deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~

            unzip -o deploy.zip

            php artisan migrate --force

            php artisan config:clear
            php artisan route:clear
            php artisan view:clear

            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            rm -f deploy.zip